sudo: required
language: c

env:
  - CABALVER=1.24 GHCVER=8.0.1

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install: cabal update && cabal install hspec

script:
  - runhaskell -isrc ./tests/ProductoTest.hs
  - runhaskell -isrc ./tests/SumaTest.hs
